apiVersion: v1
kind: Secret # Store in SSM or Vault, it treats the data as base64 encoded
metadata:
  name: code-secret
  namespace: codens
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=
  SUDO_PASSWORD: cGFzc3dvcmQ=
