---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakeapi-deploy
  namespace: fakeapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fakeapi
  template:
    metadata:
      name: fakepi-po
      labels:
        app: fakeapi
    spec:
      containers:
        - name: fakeapi-container
          image: chukmunnlee/fakeapi:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: fakeapi-svc
  namespace: fakeapi
spec:
  selector:
    app: fakeapi
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fakeapi-ing
  namespace: fakeapi
spec:
  ingressClassName: nginx
  rules:
    - host: fakeapi-139.59.219.226.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fakeapi-svc
                port:
                  number: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fakeapi-hpa
  namespace: fakeapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fakeapi-deploy
  minReplicas: 1
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 30
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10
---
apiVersion: v1
kind: Service
metadata:
  name: fakeapi-svc
  namespace: fakeapi
spec:
  clusterIP: None
  selector:
    app: fakeapi
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
