---
apiVersion: v1
kind: Namespace
metadata:
  name: dbns
---
apiVersion: v1
kind: Service
metadata:
  name: db-hsvc
  namespace: dbns
spec:
  clusterIP: None
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: db-po
---
apiVersion: apps/v1
kind: StatefulSet # like Deployment, but with persistent storage
metadata:
  name: db-sts
  namespace: dbns
spec:
  selector:
    matchLabels:
      app: db-po
  serviceName: db-hsvc # Headless service
  replicas: 1
  volumeClaimTemplates:
    - metadata:
        name: db-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: do-block-storage
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      name: db-po
      labels:
        app: db-po
    spec:
      containers:
        - name: db-container
          image: mysql:8
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: db-pvc
              mountPath: /var/lib/mysql
