---
apiVersion: v1
kind: Secret # Store in SSM or Vault, it treats the data as base64 encoded
metadata:
  name: minio-secret
  namespace: minio-ns
type: Opaque
data:
  MINIO_ROOT_USER: YWRtaW4=
  MINIO_ROOT_PASSWORD: cGFzc3dvcmQ=
