apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: devns
commonLabels:
  env: dev

namePrefix: dev-

replicas:
  - name: dov-bear
    count: 1

images:
  - name: chukmunnlee/dov-bear
    newTag: v5

configMapGenerator:
  - name: dov-cm
    literals:
      - INSTANCE_NAME="my dev bear"
      - INSTANCE_HASH=$(POD_IP)

patches:
  - target:
      kind: Ingress
      name: dov-ing
    path: dov-ing-patches.yaml
